src/components/navbar.tsx

fix: switch to tertiary button

---

src/components/navbar.tsx
src/components/network-info.tsx

This PR
* shows a label with network name if on testnet or devnet
* fixes #42

Show testnet label if testnet

---

src/pages/choose-stacking-method/use-stacking-initiated-by.ts

This PR
* adds extra logic for FAST pool when determining who initiated the stacking 
* fixes #37

fix: find correct initiator for self-service pool

---

src/pages/stacking/start-pooled-stacking/components/pool-select-item.tsx

This PR
* adds pointer cursor to pool select items
* fixes #55

Add cursor to pool select items

---

src/pages/stacking/start-pooled-stacking/components/preset-pools.tsx
src/pages/stacking/start-pooled-stacking/types-preset-pools.ts
src/pages/stacking/start-pooled-stacking/utils-delegate-stx.ts

This PR
* adds a minimum per pool for the delegation amount. This impact the validation of the amount field only
* fixes #62

Add minimum delegation amount per pool

---

src/app.tsx
src/components/finished-tx-result-info.tsx
src/pages/stacking/pool-admin/components/choose-amount.tsx
src/pages/stacking/pool-admin/components/choose-duration.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle.tsx
src/pages/stacking/pool-admin/components/choose-stacker.tsx
src/pages/stacking/pool-admin/components/choose-start-burn-height.tsx
src/pages/stacking/pool-admin/components/pool-admin-intro.tsx
src/pages/stacking/pool-admin/components/pool-admin-layout.tsx
src/pages/stacking/pool-admin/delegate-stack-stx/components/confirm-and-submit.tsx
src/pages/stacking/pool-admin/delegate-stack-stx/components/delegate-stack-stx-info-card.tsx
src/pages/stacking/pool-admin/delegate-stack-stx/delegate-stack-stx.tsx
src/pages/stacking/pool-admin/delegate-stack-stx/types.ts
src/pages/stacking/pool-admin/delegate-stack-stx/utils.ts
src/pages/stacking/pool-admin/stack-aggregation-commit/components/confirm-and-submit.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/components/stack-aggregate-commit-info-card.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/stack-aggregation-commit.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/types.ts
src/pages/stacking/pool-admin/stack-aggregation-commit/utils.ts
src/pages/stacking/start-pooled-stacking/utils-delegate-stx.ts
src/pages/stacking/start-pooled-stacking/utils-disallow-contract-caller.ts
src/pages/stacking/start-pooled-stacking/utils.ts

This PR
* adds a new form for delegate-stack-stx
* adds a new form for stack-aggregation-commit

Pool admin page

---

src/components/footer.tsx

This PR
* adds a link to the git repo in the footer
* fixes #78

Add link to source code

---

src/app.tsx
src/components/stacking-client-provider/stacking-client-provider.tsx
src/components/tooltip.tsx
src/constants/routes.ts
src/pages/choose-stacking-method/components/start-stacking-layout.tsx
src/pages/stacking/direct-stacking-info/get-has-pending-direct-stacking.ts
src/pages/stacking/direct-stacking-info/get-has-pending-stack-extend.ts
src/pages/stacking/direct-stacking-info/get-has-pending-stack-increase.ts
src/pages/stacking/direct-stacking-info/use-get-has-pending-tx-query.ts
src/pages/stacking/direct-stacking-info/utils-pending-txs.ts
src/pages/stacking/pool-admin/components/choose-stacker.tsx
src/pages/stacking/pooled-stacking-info/components/content-active-pooling.tsx
src/pages/stacking/pooled-stacking-info/components/content-expired-pooling.tsx
src/pages/stacking/pooled-stacking-info/components/content-revoked-while-stacking.tsx
src/pages/stacking/pooled-stacking-info/components/increase-pooling-amount.tsx
src/pages/stacking/pooled-stacking-info/components/no-pooling.tsx
src/pages/stacking/pooled-stacking-info/components/percentage-row.tsx
src/pages/stacking/pooled-stacking-info/components/progress-row.tsx
src/pages/stacking/pooled-stacking-info/components/self-service-rows.tsx
src/pages/stacking/pooled-stacking-info/get-delegation-status.ts
src/pages/stacking/pooled-stacking-info/pooled-stacking-info.tsx
src/pages/stacking/pooled-stacking-info/use-delegation-status-query.ts
src/pages/stacking/pooled-stacking-info/use-get-pool-address-query.ts
src/pages/stacking/self-service-extend/components/choose-stacker.tsx
src/pages/stacking/self-service-extend/components/self-service-extend-layout.tsx
src/pages/stacking/self-service-extend/components/stacker-details-rows.tsx
src/pages/stacking/self-service-extend/self-service-extend.tsx
src/pages/stacking/self-service-extend/utils.ts
src/pages/stacking/stack-extend/components/stack-extend-layout.tsx
src/pages/stacking/start-pooled-stacking/types-preset-pools.ts

This PR
* builds on top of #88 
* adds a button to increase the pooled amount
* adds a button for users to do self-service pooling
* fixes #64 
https://loom.com/share/a0904befaed74a0491935e5e2e95e93d

Update stacking for pooled stackers

---

src/components/pox-disabled-layout.tsx

This PR
* adds a link to the info screen about sip 22

Add link to sip 22

---

src/components/drawer/base-drawer.tsx

This PR
* replaces #120 to fix merge queue issue

Use bg color instead of white

---

src/pages/stacking/start-pooled-stacking/utils-delegate-stx.ts

This PR
* adds none for list of optional metadata for 1-cycle pools

Fix 1-cycle pools

---

src/pages/stacking/start-pooled-stacking/utils-preset-pools.ts

Fix array includes

---

src/pages/stacking/stack-increase/components/stack-increase-layout.tsx
src/pages/stacking/stack-increase/stack-increase.tsx
src/pages/stacking/stack-increase/utils.ts

This PR
* re-adds stacks-increase form
* fixes #137

Re-add stacks-increase form

---

src/pages/stacking/pool-admin/delegate-stack-extend/delegate-stack-extend.tsx
src/pages/stacking/pool-admin/delegate-stack-increase/delegate-stack-increase.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/stack-aggregation-commit.tsx
src/pages/stacking/pool-admin/stack-aggregation-increase/stack-aggregation-increase.tsx
src/pages/stacking/start-direct-stacking/components/choose-amount.tsx
src/pages/stacking/start-direct-stacking/start-direct-stacking.tsx

This PR
* changes the check for stx balance type from string to bigint, the new type returned from the api

Change type of balance to bigint

---

src/pages/choose-stacking-method/choose-stacking-method.layout.tsx
src/pages/choose-stacking-method/components/bridging-step-card.tsx
src/pages/choose-stacking-method/components/enroll-for-sbtc-rewards.tsx
src/pages/choose-stacking-method/components/section-hero.tsx
src/pages/choose-stacking-method/components/start-stacking-layout.tsx

- **Unhides sBTC section**
- Adds disclaimer modal upon clicking enroll
- Adds "learn more" links to section heroes
- Fixes double border issue for cards

Add enroll modal, more landing page improvements

---

src/pages/stacking/start-pooled-stacking/components/preset-pools.tsx
src/pages/stacking/start-pooled-stacking/types-preset-pools.ts

1. Added Stacking DAO as an option to stack in our non-custodial pool
2. Sorted all pools alphabetically

feat: add Stacking DAO native pool

---

src/components/circle-button.tsx
src/components/error-text.tsx
src/pages/choose-stacking-method/choose-stacking-method.tsx
src/pages/sign-in/sign-in.tsx
src/pages/stacking/components/pending-stack-extend-alert.tsx
src/pages/stacking/components/pending-stack-increase-alert.tsx
src/pages/stacking/components/stacking-form-container.tsx
src/pages/stacking/pool-admin/components/pool-admin-layout.tsx
src/pages/stacking/self-service-extend/components/self-service-extend-layout.tsx
src/pages/stacking/start-direct-stacking/components/direct-stacking-intro.tsx
src/pages/stacking/start-pooled-stacking/components/duration-cycles-field.tsx
src/pages/stacking/start-pooled-stacking/components/pool-contract-allow.tsx
src/pages/stacking/start-pooled-stacking/components/preset-pools.tsx

This is first pr to remove stacks ui from the app

refactor: remove stacks ui, part 1

---

src/components/drawer/components/header-action-button.tsx
src/components/hr.tsx
src/components/icons/revoked-delegation-icon.tsx
src/components/icons/success-checkmark.tsx
src/components/info-card.tsx
src/pages/settings/network/network-items.tsx
src/pages/stacking/components/one-cycle-descriptor.tsx
src/pages/stacking/components/stacker-details-rows.tsx
src/pages/stacking/components/stacking-description.tsx
src/pages/stacking/components/stacking-form-container.tsx
src/pages/stacking/components/stepper.tsx
src/pages/stacking/direct-stacking-info/components/no-stacking-info.tsx
src/pages/stacking/pool-admin/components/balances.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle.tsx
src/pages/stacking/pool-admin/delegate-stack-extend/components/delegate-stack-extend-info-card.tsx
src/pages/stacking/pool-admin/delegate-stack-increase/components/delegate-stack-increase-info-card.tsx
src/pages/stacking/pool-admin/pool-info/components/pool-info-card.tsx
src/pages/stacking/pooled-stacking-info/components/content-active-pooling.tsx
src/pages/stacking/signer/generate-signature/components/topic.tsx
src/pages/stacking/start-pooled-stacking/components/duration-cycles-field.tsx

This is 2 pr to remove stacks ui from the app

refactor: remove stacks ui, part 2

---

src/pages/choose-stacking-method/components/start-stacking-layout.tsx
src/pages/stacking/pool-admin/components/choose-duration.tsx
src/pages/stacking/pool-admin/delegate-stack-stx/components/delegate-stack-stx-info-card.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/components/stack-aggregate-commit-info-card.tsx
src/pages/stacking/pooled-stacking-info/pooled-stacking-info.tsx
src/pages/stacking/self-service-extend/components/extend-for-current-user.tsx
src/pages/stacking/self-service-extend/components/stacker-details-rows-for-extend.tsx
src/pages/stacking/self-service-extend/self-service-extend.tsx
src/pages/stacking/signer/generate-signature/components/signature-section.tsx
src/pages/stacking/signer/signer-info/components/signer-info-layout.tsx
src/pages/stacking/stack-extend/stack-extend.tsx
src/pages/stacking/start-direct-stacking/components/duration.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-amount.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-protocol.tsx
src/pages/stacking/start-liquid-stacking/components/protocol-select-item.tsx
src/pages/stacking/start-liquid-stacking/components/stacking-form-step.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pool-stx-address.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-duration.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-pool.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-reward-address.tsx
src/pages/stacking/start-pooled-stacking/components/custom-pool-address-input.tsx
src/pages/stacking/start-pooled-stacking/components/delegated-stacking-terms.tsx
src/pages/stacking/start-pooled-stacking/components/duration-select-item.tsx
src/pages/stacking/start-pooled-stacking/components/indefinite-stacking-icon.tsx
src/pages/stacking/start-pooled-stacking/components/limited-stacking-icon.tsx
src/pages/stacking/start-pooled-stacking/components/pool-contract-disallow-button.tsx
src/pages/stacking/start-pooled-stacking/components/preset-pooling-reward-address-info.tsx
src/pages/stacking/start-pooled-stacking/components/stacking-form-step.tsx

refactor: pull out stacks ui part 3

---

src/components/add-network-form.tsx
src/pages/choose-stacking-method/components/start-stacking-layout.tsx
src/pages/stacking/pool-admin/components/choose-amount.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle-index.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle.tsx
src/pages/stacking/pool-admin/components/choose-stacker.tsx
src/pages/stacking/pool-admin/components/choose-start-burn-height.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/components/signer-details.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-amount.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-protocol.tsx
src/pages/stacking/start-liquid-stacking/components/stacking-form-step.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-duration.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-pool.tsx
src/pages/stacking/start-pooled-stacking/components/duration-select-item.tsx
src/pages/stacking/start-pooled-stacking/components/pool-select-item.tsx

contains refactor of inputs (part of them)

refactor: pull out stacks ui part 5

---

package.json
pnpm-lock.yaml
src/components/add-network-form.tsx
src/components/address.tsx
src/pages/choose-stacking-method/components/start-stacking-layout.tsx
src/pages/stacking/pool-admin/components/choose-amount.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle-index.tsx
src/pages/stacking/pool-admin/components/choose-reward-cycle.tsx
src/pages/stacking/pool-admin/components/choose-stacker.tsx
src/pages/stacking/pool-admin/components/choose-start-burn-height.tsx
src/pages/stacking/pool-admin/stack-aggregation-commit/components/signer-details.tsx
src/pages/stacking/pool-admin/stack-aggregation-increase/components/stack-aggregate-increase-info-card.tsx
src/pages/stacking/pooled-stacking-info/components/content-expired-pooling.tsx
src/pages/stacking/pooled-stacking-info/components/content-revoked-while-stacking.tsx
src/pages/stacking/pooled-stacking-info/components/increase-pooling-amount.tsx
src/pages/stacking/pooled-stacking-info/components/no-pooling.tsx
src/pages/stacking/signer/generate-signature/components/generate-signature-layout.tsx
src/pages/stacking/stack-increase/components/stack-increase-layout.tsx
src/pages/stacking/stack-increase/stack-increase.tsx
src/pages/stacking/start-direct-stacking/components/direct-stacking-terms.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-amount.tsx
src/pages/stacking/start-liquid-stacking/components/choose-stacking-protocol.tsx
src/pages/stacking/start-liquid-stacking/components/stacking-form-step.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-duration.tsx
src/pages/stacking/start-pooled-stacking/components/choose-pooling-pool.tsx
src/pages/stacking/start-pooled-stacking/components/duration-select-item.tsx
src/pages/stacking/start-pooled-stacking/components/pool-select-item.tsx

the 4th part of stacks ui pull out
next big part is refactoring forms (input component)

refactor: pull out stacks ui part 4

---

src/components/blockchain-api-client-provider.tsx
src/components/stacking-client-provider/fetch-fn.ts
src/components/stacking-client-provider/stacking-client-provider.tsx
src/pages/stacking/components/stacking-for-user-form-container.tsx
src/pages/stacking/pool-admin/delegate-stack-extend/components/delegate-stack-extend-info-card.tsx
src/pages/stacking/pool-admin/delegate-stack-increase/components/delegate-stack-increase-info-card.tsx
src/pages/stacking/pool-admin/delegate-stack-increase/utils.ts
src/pages/stacking/self-service-extend/components/extend-for-current-user.tsx
src/pages/stacking/self-service-extend/components/extend-for-other-user.tsx

Earn was missing some header details that might alleviate some of the request errors. I'm in transit and not able to test thoroughly rn though. Draft until I can test.
cc/ @314159265359879 @friedger

fix: reports of 429 errors

---

src/pages/stacking/start-pooled-stacking/components/choose-pooling-duration.tsx

fix-typo-in-choose-pooling-duration

---

src/components/banner.tsx
src/components/navbar.tsx

**not to merge until actual release**

feat: link to new stacking app

---

src/components/banner.tsx

fix: more prominent banner color
